name: Refresh OpenAlex data

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug checkout
        run: |
          pwd
          ls -la
          git status
          echo "Branch: $GITHUB_REF"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install requests

      - name: Build JSON
        env:
          OPENALEX_MAILTO: ${{ secrets.OPENALEX_MAILTO || 'YOUR_EMAIL@example.com' }}
        run: |
          set -e
          python scripts/build.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add site/data/authors.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: refresh data"
            git push
          fi
