name: Refresh OpenAlex data

on:
  schedule:
    - cron: '5 0 * * *'   # daily 00:05 UTC
  workflow_dispatch: {}

permissions:
  contents: write

defaults:
  run:
    working-directory: openalex-scholar-dashboard

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug paths
        run: |
          pwd
          ls -la
          ls -la scripts || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build JSON
        env:
          OPENALEX_MAILTO: ${{ secrets.OPENALEX_MAILTO || 'YOUR_EMAIL@example.com' }}
        run: python scripts/build.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add site/data/authors.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: refresh data"
            git push
          fi
